/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Acelerometro.c
**     CDE edition : Standard
**     Project     : ZZZ_Robocol
**     Processor   : MKL46Z256VLL4
**     Component   : MMA8451Q
**     Version     : Component 01.036, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-06-12, 18:39, # CodeGen: 34
**     Abstract    :
**         Implements a Driver for the MMA8451 accelerometer from Freescale.
**     Settings    :
**          Component Name                                 : Acelerometro
**          Slave Address                                  : 1D
**          I2C Bus                                        : GI2C1
**          Constant Offsets                               : Enabled
**            X offset                                     : 0
**            Y offset                                     : 0
**            Z offset                                     : 0
**          Shell                                          : Disabled
**     Contents    :
**         Enable         - uint8_t Acelerometro_Enable(void);
**         Disable        - uint8_t Acelerometro_Disable(void);
**         isEnabled      - uint8_t Acelerometro_isEnabled(bool *isEnabled);
**         SwReset        - uint8_t Acelerometro_SwReset(void);
**         ReadReg8       - uint8_t Acelerometro_ReadReg8(void* addr, void* *val);
**         WriteReg8      - uint8_t Acelerometro_WriteReg8(void* addr, void* val);
**         GetX           - int16_t Acelerometro_GetX(void);
**         GetY           - int16_t Acelerometro_GetY(void);
**         GetZ           - int16_t Acelerometro_GetZ(void);
**         GetRaw8XYZ     - uint8_t Acelerometro_GetRaw8XYZ(void* *xyz);
**         CalibrateX1g   - void Acelerometro_CalibrateX1g(void);
**         CalibrateY1g   - void Acelerometro_CalibrateY1g(void);
**         CalibrateZ1g   - void Acelerometro_CalibrateZ1g(void);
**         GetXmg         - int16_t Acelerometro_GetXmg(void);
**         GetYmg         - int16_t Acelerometro_GetYmg(void);
**         GetZmg         - int16_t Acelerometro_GetZmg(void);
**         MeasureGetRawX - uint16_t Acelerometro_MeasureGetRawX(void);
**         MeasureGetRawY - uint16_t Acelerometro_MeasureGetRawY(void);
**         MeasureGetRawZ - uint16_t Acelerometro_MeasureGetRawZ(void);
**         GetXOffset     - int16_t Acelerometro_GetXOffset(void);
**         GetYOffset     - int16_t Acelerometro_GetYOffset(void);
**         GetZOffset     - int16_t Acelerometro_GetZOffset(void);
**         GetX1gValue    - int16_t Acelerometro_GetX1gValue(void);
**         GetY1gValue    - int16_t Acelerometro_GetY1gValue(void);
**         GetZ1gValue    - int16_t Acelerometro_GetZ1gValue(void);
**         SetFastMode    - uint8_t Acelerometro_SetFastMode(bool on);
**         WhoAmI         - uint8_t Acelerometro_WhoAmI(void* *value);
**         Init           - uint8_t Acelerometro_Init(void);
**         Deinit         - uint8_t Acelerometro_Deinit(void);
**
**     License : Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2013-2014, all rights reserved.
**     http://www.mcuoneclipse.com
**     This an open source software in the form of a Processor Expert Embedded Component.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file Acelerometro.c
** @version 01.00
** @brief
**         Implements a Driver for the MMA8451 accelerometer from Freescale.
*/         
/*!
**  @addtogroup Acelerometro_module Acelerometro module documentation
**  @{
*/         

/* MODULE Acelerometro. */

#include "Acelerometro.h"

#define Acelerometro_CPU_IS_LITTLE_ENDIAN 1 /* Cpu is little endian */

typedef struct {
  int16_t NxOff; /* offset for X axis */
  int16_t NyOff; /* offset for Y axis */
  int16_t NzOff; /* offset for Z axis */
} tAccelCal;

/* default calibration values from component properties */
static const tAccelCal InitialCalibration = { /* Initial default calibration values */
  0, /* X offset */
  0, /* Y offset */
  0, /* Z offset */
};
static tAccelCal sCalValues; /* calibration values in RAM */

#define CalNxOff   sCalValues.NxOff
#define CalNyOff   sCalValues.NyOff
#define CalNzOff   sCalValues.NzOff

/*
** ===================================================================
**     Method      :  Acelerometro_GetRaw8XYZ (component MMA8451Q)
**     Description :
**         Returns in an array the x, y and z accelerometer as 8bit
**         values.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * xyz             - Pointer to an array of three unsigned 8bit
**                           values which are used to return the
**                           accelerometer values.
**     Returns     :
**         ---             - Error code, ERR_OK for no error.
** ===================================================================
*/
uint8_t Acelerometro_GetRaw8XYZ(uint8_t *xyz)
{
  static const uint8_t addr = Acelerometro_OUT_X_MSB;

  return GI2C1_ReadAddress(Acelerometro_I2C_ADDR, (uint8_t*)&addr, sizeof(addr), &xyz[0], 3);
}

/*
** ===================================================================
**     Method      :  Acelerometro_Deinit (component MMA8451Q)
**     Description :
**         Counterpart to Init() method.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, ERR_OK if everything is ok.
** ===================================================================
*/
uint8_t Acelerometro_Deinit(void)
{
  return ERR_OK; /* nothing to do */
}

/*
** ===================================================================
**     Method      :  Acelerometro_Init (component MMA8451Q)
**     Description :
**         Initializes the device driver
**     Parameters  : None
**     Returns     :
**         ---             - Error code, ERR_OK if everything is ok.
** ===================================================================
*/
uint8_t Acelerometro_Init(void)
{
  sCalValues.NxOff = InitialCalibration.NxOff;
  sCalValues.NyOff = InitialCalibration.NyOff;
  sCalValues.NzOff = InitialCalibration.NzOff;
  return GI2C1_WriteByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_CTRL_REG_1, Acelerometro_ACTIVE_BIT_MASK); /* enable device */
}

/*
** ===================================================================
**     Method      :  Acelerometro_CalibrateX1g (component MMA8451Q)
**     Description :
**         Performs a calibration of the sensor. It is assumed that the
**         Y and Z sensors have 0 g, and the X sensor has 1 g.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Acelerometro_CalibrateX1g(void)
{
  /* assumption is that accelerometer is placed with 1g for X and 0g for Y and Z */
  int32_t X=0, Y=0, Z=0;
  uint8_t i;

  /* Get the raw data and remove 2 bits (16bit to 14bit) */
  for (i=0; i<8; i++) {
   X += ((int16_t)Acelerometro_MeasureGetRawX() >> 2);
   Y += ((int16_t)Acelerometro_MeasureGetRawY() >> 2);
   Z += ((int16_t)Acelerometro_MeasureGetRawZ() >> 2);
  }
  /* build average of 8 measured values */
  X >>= 3;
  Y >>= 3;
  Z >>= 3;
  /* store the calibration values */
  /* offset: both Y and Z shall have zero g */
  sCalValues.NzOff = (X - (1000 << 2));
  sCalValues.NyOff = Y;
  sCalValues.NzOff = Z;
}

/*
** ===================================================================
**     Method      :  Acelerometro_CalibrateY1g (component MMA8451Q)
**     Description :
**         Performs a calibration of the sensor. It is assumed that the
**         X and Z sensors have 0 g, and the Y sensor has 1 g.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Acelerometro_CalibrateY1g(void)
{
  /* assumption is that accelerometer is placed with 1g for Y and 0g for X and Z */
  int32_t X=0, Y=0, Z=0;
  uint8_t i;

  /* Get the raw data and remove 2 bits (16bit to 14bit) */
  for (i=0; i<8; i++) {
   X += ((int16_t)Acelerometro_MeasureGetRawX() >> 2);
   Y += ((int16_t)Acelerometro_MeasureGetRawY() >> 2);
   Z += ((int16_t)Acelerometro_MeasureGetRawZ() >> 2);
  }
  /* build average of 8 measured values */
  X >>= 3;
  Y >>= 3;
  Z >>= 3;
  /* store the calibration values */
  /* offset: both X and Z shall have zero g */
  sCalValues.NxOff = X;
  sCalValues.NzOff = (Y - (1000 << 2));
  sCalValues.NzOff = Z;
}

/*
** ===================================================================
**     Method      :  Acelerometro_CalibrateZ1g (component MMA8451Q)
**     Description :
**         Performs a calibration of the sensor. It is assumed that the
**         X and Y sensors have 0 g, and the Z sensor has 1 g.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Acelerometro_CalibrateZ1g(void)
{
  /* assumption is that accelerometer is placed with 1g for Z and 0g for X and Y */
  int32_t X=0, Y=0, Z=0;
  uint8_t i;

  /* Get the raw data and remove 2 bits (16bit to 14bit) */
  for (i=0; i<8; i++) {
   X += ((int16_t)Acelerometro_MeasureGetRawX() >> 2);
   Y += ((int16_t)Acelerometro_MeasureGetRawY() >> 2);
   Z += ((int16_t)Acelerometro_MeasureGetRawZ() >> 2);
  }
  /* build average of 8 measured values */
  X >>= 3;
  Y >>= 3;
  Z >>= 3;
  /* store the calibration values */
  /* offset: both X and Y shall have zero g (midpoint) */
  sCalValues.NxOff = X;
  sCalValues.NyOff = Y;
  sCalValues.NzOff = (Z - (1000 << 2));
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetXmg (component MMA8451Q)
**     Description :
**         Returns the X value in mg
**     Parameters  : None
**     Returns     :
**         ---             - The g value in 1/1000g units
** ===================================================================
*/
int16_t Acelerometro_GetXmg(void)
{
  return Acelerometro_GetX() / 4;
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetYmg (component MMA8451Q)
**     Description :
**         Returns the Y value in mg
**     Parameters  : None
**     Returns     :
**         ---             - The g value in 1/1000g units
** ===================================================================
*/
int16_t Acelerometro_GetYmg(void)
{
  return Acelerometro_GetY() / 4;
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetZmg (component MMA8451Q)
**     Description :
**         Returns the Z value in mg
**     Parameters  : None
**     Returns     :
**         ---             - The g value in 1/1000g units
** ===================================================================
*/
int16_t Acelerometro_GetZmg(void)
{
  return Acelerometro_GetZ() / 4;
}

/*
** ===================================================================
**     Method      :  Acelerometro_MeasureGetRawX (component MMA8451Q)
**     Description :
**         Performs a measurement on X channel and returns the raw
**         value.
**     Parameters  : None
**     Returns     :
**         ---             - X sensor value
** ===================================================================
*/
uint16_t Acelerometro_MeasureGetRawX(void)
{
  union {
    uint8_t buf[2]; /* value from device is in big endian */
    uint16_t be;
  } val;
  static const uint8_t addr = Acelerometro_OUT_X_MSB;

  if(GI2C1_ReadAddress(Acelerometro_I2C_ADDR, (uint8_t*)&addr, sizeof(addr), &val.buf[0], sizeof(val.buf))!=ERR_OK) {
    return 0; /* failure */
  }
#if Acelerometro_CPU_IS_LITTLE_ENDIAN
  return (uint16_t)((val.buf[0]<<8)|val.buf[1]); /* transform into LE value */
#else
  return val.be; /* already in BE */
#endif
}

/*
** ===================================================================
**     Method      :  Acelerometro_MeasureGetRawY (component MMA8451Q)
**     Description :
**         Performs a measurement on Y channel and returns the raw
**         value.
**     Parameters  : None
**     Returns     :
**         ---             - Y sensor value
** ===================================================================
*/
uint16_t Acelerometro_MeasureGetRawY(void)
{
  union {
    uint8_t buf[2]; /* value from device is in big endian */
    uint16_t be;
  } val;
  static const uint8_t addr = Acelerometro_OUT_Y_MSB;

  if(GI2C1_ReadAddress(Acelerometro_I2C_ADDR, (uint8_t*)&addr, sizeof(addr), &val.buf[0], sizeof(val.buf))!=ERR_OK) {
    return 0; /* failure */
  }
#if Acelerometro_CPU_IS_LITTLE_ENDIAN
  return (uint16_t)((val.buf[0]<<8)|val.buf[1]); /* transform into LE value */
#else
  return val.be; /* already in BE */
#endif
}

/*
** ===================================================================
**     Method      :  Acelerometro_MeasureGetRawZ (component MMA8451Q)
**     Description :
**         Performs a measurement on Z channel and returns the raw
**         value.
**     Parameters  : None
**     Returns     :
**         ---             - Z sensor value
** ===================================================================
*/
uint16_t Acelerometro_MeasureGetRawZ(void)
{
  union {
    uint8_t buf[2]; /* value from device is in big endian */
    uint16_t be;
  } val;
  static const uint8_t addr = Acelerometro_OUT_Z_MSB;

  if(GI2C1_ReadAddress(Acelerometro_I2C_ADDR, (uint8_t*)&addr, sizeof(addr), &val.buf[0], sizeof(val.buf))!=ERR_OK) {
    return 0; /* failure */
  }
#if Acelerometro_CPU_IS_LITTLE_ENDIAN
  return (uint16_t)((val.buf[0]<<8)|val.buf[1]); /* transform into LE value */
#else
  return val.be; /* already in BE */
#endif
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetXOffset (component MMA8451Q)
**     Description :
**         Returns the offset applied to the X value.
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
int16_t Acelerometro_GetXOffset(void)
{
  return CalNxOff;
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetYOffset (component MMA8451Q)
**     Description :
**         Returns the offset applied to the Y value.
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
int16_t Acelerometro_GetYOffset(void)
{
  return CalNyOff;
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetZOffset (component MMA8451Q)
**     Description :
**         Returns the offset applied to the Z value.
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
int16_t Acelerometro_GetZOffset(void)
{
  return CalNzOff;
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetX1gValue (component MMA8451Q)
**     Description :
**         Returns the value for 1g for channel  X.
**     Parameters  : None
**     Returns     :
**         ---             - 1g value for X
** ===================================================================
*/
int16_t Acelerometro_GetX1gValue(void)
{
  return 4096;
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetY1gValue (component MMA8451Q)
**     Description :
**         Returns the value for 1g for channel  Y.
**     Parameters  : None
**     Returns     :
**         ---             - 1g value for Y
** ===================================================================
*/
int16_t Acelerometro_GetY1gValue(void)
{
  return 4096;
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetZ1gValue (component MMA8451Q)
**     Description :
**         Returns the value for 1g for channel  Z.
**     Parameters  : None
**     Returns     :
**         ---             - 1g value for Z
** ===================================================================
*/
int16_t Acelerometro_GetZ1gValue(void)
{
  return 4096;
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetX (component MMA8451Q)
**     Description :
**         Retrieves the value for the X axis. The value is adjusted
**         with the zero calibration value (0 for 0 g, negative for
**         negative acceleration and positive for positive acceleration).
**     Parameters  : None
**     Returns     :
**         ---             - Measured X value
** ===================================================================
*/
int16_t Acelerometro_GetX(void)
{
  int16_t value;

  value = (int16_t)Acelerometro_MeasureGetRawX() >> 2; /* remove 2 bits (16bit to 14bit) */
  value -= CalNxOff; /* adjust with calibration offset */
  return value;
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetY (component MMA8451Q)
**     Description :
**         Retrieves the value for the Y axis. The value is adjusted
**         with the zero calibration value (0 for 0 g, negative for
**         negative acceleration and positive for positive acceleration).
**     Parameters  : None
**     Returns     :
**         ---             - Measured Y value
** ===================================================================
*/
int16_t Acelerometro_GetY(void)
{
  int16_t value;

  value = (int16_t)Acelerometro_MeasureGetRawY() >> 2; /* remove 2 bits (16bit to 14bit) */
  value -= CalNyOff; /* adjust with calibration offset */
  return value;
}

/*
** ===================================================================
**     Method      :  Acelerometro_GetZ (component MMA8451Q)
**     Description :
**         Retrieves the value for the Z axis. The value is adjusted
**         with the zero calibration value (0 for 0 g, negative for
**         negative acceleration and positive for positive acceleration).
**     Parameters  : None
**     Returns     :
**         ---             - Measured Z value
** ===================================================================
*/
int16_t Acelerometro_GetZ(void)
{
  int16_t value;

  value = (int16_t)Acelerometro_MeasureGetRawZ() >> 2; /* remove 2 bits (16bit to 14bit) */
  value -= CalNzOff; /* adjust with calibration offset */
  return value;
}

/*
** ===================================================================
**     Method      :  Acelerometro_SetFastMode (component MMA8451Q)
**     Description :
**         Turns the F_READ (Fast Read Mode) on or off
**     Parameters  :
**         NAME            - DESCRIPTION
**         on              - if to turn the F_READ mode on or off
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t Acelerometro_SetFastMode(bool on)
{
  uint8_t val, res;

  res = GI2C1_ReadByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_CTRL_REG_1, &val);
  if (res!=ERR_OK) {
    return res;
  }
  if (on) {
    val |= Acelerometro_F_READ_BIT_MASK; /* enable F_READ: Fast read mode, data format limited to single byte (auto increment counter will skip LSB) */
  } else {
    val &= ~Acelerometro_F_READ_BIT_MASK; /* disable F_READ: Fast read mode, data format limited to single byte (auto increment counter will skip LSB) */
  }
  return GI2C1_WriteByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_CTRL_REG_1, val);
}

/*
** ===================================================================
**     Method      :  Acelerometro_Enable (component MMA8451Q)
**     Description :
**         Enables the device with setting the ACTIVE bit in the CTRL
**         register 1
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t Acelerometro_Enable(void)
{
  uint8_t val, res;

  res = GI2C1_ReadByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_CTRL_REG_1, &val);
  if (res!=ERR_OK) {
    return res;
  }
  if (val&Acelerometro_ACTIVE_BIT_MASK) {
    return ERR_OK; /* already enabled */
  }
  WAIT1_Waitms(1); /* for unknown reasons, need to wait for 1 ms after reading the register */
  val |= Acelerometro_ACTIVE_BIT_MASK; /* enable device */
  return GI2C1_WriteByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_CTRL_REG_1, val);
}

/*
** ===================================================================
**     Method      :  Acelerometro_Disable (component MMA8451Q)
**     Description :
**         Disables the device with clearing the ACTIVE bit in the CTRL
**         register 1
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t Acelerometro_Disable(void)
{
  uint8_t val, res;

  res = GI2C1_ReadByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_CTRL_REG_1, &val);
  if (res!=ERR_OK) {
    return res;
  }
  if ((val&Acelerometro_ACTIVE_BIT_MASK)==0) {
    return ERR_OK; /* already disabled */
  }
  WAIT1_Waitms(1); /* for unknown reasons, need to wait for 1 ms after reading the register */
  val &= ~Acelerometro_ACTIVE_BIT_MASK; /* disable device */
  return GI2C1_WriteByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_CTRL_REG_1, val);
}

/*
** ===================================================================
**     Method      :  Acelerometro_isEnabled (component MMA8451Q)
**     Description :
**         Returns the status of the the ACTIVE bit in the CTRL
**         register 1
**     Parameters  :
**         NAME            - DESCRIPTION
**       * isEnabled       - Pointer to where to store the
**                           result, TRUE if ACTIVE bit is set, FALSE
**                           otherwise
**     Returns     :
**         ---             - error code
** ===================================================================
*/
uint8_t Acelerometro_isEnabled(bool *isEnabled)
{
  uint8_t val, res;

  res = GI2C1_ReadByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_CTRL_REG_1, &val);
  if (res!=ERR_OK) {
    *isEnabled = FALSE;
    return ERR_FAILED;
  }
  *isEnabled = (val&Acelerometro_ACTIVE_BIT_MASK)!=0; /* TRUE if bit is set, FALSE otherwise */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  Acelerometro_WhoAmI (component MMA8451Q)
**     Description :
**         Returns the value of the WHO_AM_I (0x0D) register
**     Parameters  :
**         NAME            - DESCRIPTION
**       * value           - Pointer to value to store
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t Acelerometro_WhoAmI(uint8_t *value)
{
  return GI2C1_ReadByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_WHO_AM_I, value);
}

/*
** ===================================================================
**     Method      :  Acelerometro_ReadReg8 (component MMA8451Q)
**     Description :
**         Reads an 8bit device register
**     Parameters  :
**         NAME            - DESCRIPTION
**       * addr            - device memory map address
**       * val             - Pointer to value
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t Acelerometro_ReadReg8(uint8_t addr, uint8_t *val)
{
  if (GI2C1_ReadByteAddress8(Acelerometro_I2C_ADDR, addr, val)!=ERR_OK) {
    return ERR_FAILED;
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  Acelerometro_WriteReg8 (component MMA8451Q)
**     Description :
**         Write an 8bit device register
**     Parameters  :
**         NAME            - DESCRIPTION
**       * addr            - device memory map address
**       * val             - value to write
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t Acelerometro_WriteReg8(uint8_t addr, uint8_t val)
{
  return GI2C1_WriteByteAddress8(Acelerometro_I2C_ADDR, addr, val);
}

/*
** ===================================================================
**     Method      :  Acelerometro_SwReset (component MMA8451Q)
**     Description :
**         Perform a software reset using the rst bit in the CTRL
**         register 2
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint8_t Acelerometro_SwReset(void)
{
  uint8_t val, res;

  res = GI2C1_ReadByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_CTRL_REG_2, &val);
  if (res!=ERR_OK) {
    return res;
  }
  val |= Acelerometro_CTRL_REG_2_MASK_RST; /* reset device */
  res = GI2C1_WriteByteAddress8(Acelerometro_I2C_ADDR, Acelerometro_CTRL_REG_2, val);
  if (res!=ERR_OK) {
    return res;
  }
  WAIT1_Waitms(1); /* wait for one ms after sending the software reset */
  return ERR_OK;
}

/* END Acelerometro. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
