/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PE_LDD.h
**     Project     : ZZZ_Robocol
**     Processor   : MKL46Z256VLL4
**     Version     : Component 01.003, Driver 01.04, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-03-25, 16:07, # CodeGen: 32
**     Abstract    :
**
**     Settings    :
**
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file PE_LDD.h                                                  
** @version 01.04
** @brief
**
*/         
/*!
**  @addtogroup PE_LDD_module PE_LDD module documentation
**  @{
*/         
#ifndef __PE_LDD_H
#define __PE_LDD_H

/* MODULE PE_LDD. */

#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "Acelerometro.h"
#include "AdcTemp.h"
#include "AdcLdd1.h"
#include "RingBuffer.h"
#include "GI2C1.h"
#include "ComGalileo.h"
#include "WAIT1.h"
#include "CI2C1.h"
#include "TU2.h"
#include "Oruga1BackwardPWM.h"
#include "PwmLdd2.h"
#include "BrazoFrontalForwardPWM.h"
#include "PwmLdd3.h"
#include "TU3.h"
#include "Oruga1ForwardPWM.h"
#include "PwmLdd1.h"
#include "Oruga2BackwardPWM.h"
#include "PwmLdd4.h"
#include "TU1.h"
#include "BrazoPostForwardPWM.h"
#include "PwmLdd8.h"
#include "Oruga2ForwardPWM.h"
#include "PwmLdd5.h"
#include "BrazoFrontalBackwardPWM.h"
#include "PwmLdd6.h"
#include "BrazoPostBackwardPWM.h"
#include "PwmLdd7.h"
#include "BateriaInput.h"
#include "BitsIoLdd1.h"
#include "Luz.h"
#include "BitIoLdd1.h"
#include "Buzzer.h"
#include "BitIoLdd2.h"
#include "Rng1Gal.h"
#include "AS1.h"
#include "MAG1.h"


/*
** ===================================================================
** Function prototypes
** ===================================================================
*/

/*
** ===================================================================
**     Method      :  Cpu_PE_FillMemory (component MKL46Z256LL4)
*/
/*!
**     @brief
**         Fills a memory area block by a specified value.
**     @param
**       SourceAddressPtr - Source address pointer.
**     @param
**       c - A value used to fill a memory block.
**     @param
**       len - Length of a memory block to fill.
*/
/* ===================================================================*/
void PE_FillMemory(register void* SourceAddressPtr, register uint8_t c, register uint32_t len);

/*
** ===================================================================
**     Method      :  Cpu_PE_PeripheralUsed (component MKL46Z256LL4)
*/
/*!
**     @brief
**         Returns information whether a peripheral is allocated by PEx 
**         or not.
**     @param
**       PrphBaseAddress - Base address of a peripheral.
**     @return
**       TRUE if a peripheral is used by PEx or FALSE if it isn't used.
*/
/* ===================================================================*/
bool PE_PeripheralUsed(uint32_t PrphBaseAddress);

/*
** ===================================================================
**     Method      :  Cpu_LDD_SetClockConfiguration (component MKL46Z256LL4)
*/
/*!
**     @brief
**         Changes the clock configuration of all LDD components in a 
**         project.
**     @param
**       ClockConfiguration - New CPU clock configuration changed by CPU SetClockConfiguration method.
*/
/* ===================================================================*/
void LDD_SetClockConfiguration(LDD_TClockConfiguration ClockConfiguration);

/* END PE_LDD. */


#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
