/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : RingBuffer.c
**     Project     : ZZZ_Robocol
**     Processor   : MKL46Z256VLL4
**     Component   : RingBufferUInt8
**     Version     : Component 01.003, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-06-12, 18:39, # CodeGen: 34
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         Put             - byte RingBuffer_Put(byte elem);
**         Get             - byte RingBuffer_Get(byte *elemP);
**         NofElements     - byte RingBuffer_NofElements(void);
**         NofFreeElements - byte RingBuffer_NofFreeElements(void);
**         Init            - void RingBuffer_Init(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     This an open source software of an embedded component for Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file RingBuffer.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup RingBuffer_module RingBuffer module documentation
**  @{
*/         

/* MODULE RingBuffer. */

#include "RingBuffer.h"

static uint8_t RingBuffer_buffer[RingBuffer_BUF_SIZE]; /* ring buffer */
static uint8_t RingBuffer_inIdx;  /* input index */
static uint8_t RingBuffer_outIdx; /* output index */
static uint8_t RingBuffer_inSize; /* size of input data */
/*
** ===================================================================
**     Method      :  RingBuffer_Put (component RingBufferUInt8)
**     Description :
**         Puts a new element into the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**         elem            - New element to be put into the buffer
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte RingBuffer_Put(byte elem)
{
  byte res = ERR_OK;

  EnterCritical();
  if (RingBuffer_inSize==RingBuffer_BUF_SIZE) {
    res = ERR_TXFULL;
  } else {
    RingBuffer_buffer[RingBuffer_inIdx] = elem;
    RingBuffer_inSize++;
    RingBuffer_inIdx++;
    if (RingBuffer_inIdx==RingBuffer_BUF_SIZE) {
      RingBuffer_inIdx = 0;
    }
  }
  ExitCritical();
  return res;
}

/*
** ===================================================================
**     Method      :  RingBuffer_Get (component RingBufferUInt8)
**     Description :
**         Removes an element from the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte RingBuffer_Get(byte *elemP)
{
  byte res = ERR_OK;

  EnterCritical();
  if (RingBuffer_inSize==0) {
    res = ERR_RXEMPTY;
  } else {
    *elemP = RingBuffer_buffer[RingBuffer_outIdx];
    RingBuffer_inSize--;
    RingBuffer_outIdx++;
    if (RingBuffer_outIdx==RingBuffer_BUF_SIZE) {
      RingBuffer_outIdx = 0;
    }
  }
  ExitCritical();
  return res;
}

/*
** ===================================================================
**     Method      :  RingBuffer_NofElements (component RingBufferUInt8)
**     Description :
**         Returns the actual number of elements in the buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
byte RingBuffer_NofElements(void)
{
  return RingBuffer_inSize;
}

/*
** ===================================================================
**     Method      :  RingBuffer_NofFreeElements (component RingBufferUInt8)
**     Description :
**         Returns the actual number of free elements/space in the
**         buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
byte RingBuffer_NofFreeElements(void)
{
  return (byte)(RingBuffer_BUF_SIZE-RingBuffer_inSize);
}

/*
** ===================================================================
**     Method      :  RingBuffer_Init (component RingBufferUInt8)
**     Description :
**         Initializes the data structure
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void RingBuffer_Init(void)
{
  RingBuffer_inIdx = 0;
  RingBuffer_outIdx = 0;
  RingBuffer_inSize = 0;
}

/* END RingBuffer. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
