/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Rng1Gal.c
**     Project     : ZZZ_Robocol
**     Processor   : MKL46Z256VLL4
**     Component   : RingBufferUInt8
**     Version     : Component 01.003, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-03-25, 16:07, # CodeGen: 32
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         Put             - byte Rng1Gal_Put(byte elem);
**         Get             - byte Rng1Gal_Get(byte *elemP);
**         NofElements     - byte Rng1Gal_NofElements(void);
**         NofFreeElements - byte Rng1Gal_NofFreeElements(void);
**         Init            - void Rng1Gal_Init(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2012, all rights reserved.
**     This an open source software of an embedded component for Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file Rng1Gal.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Rng1Gal_module Rng1Gal module documentation
**  @{
*/         

/* MODULE Rng1Gal. */

#include "Rng1Gal.h"

static uint8_t Rng1Gal_buffer[Rng1Gal_BUF_SIZE]; /* ring buffer */
static uint8_t Rng1Gal_inIdx;  /* input index */
static uint8_t Rng1Gal_outIdx; /* output index */
static uint8_t Rng1Gal_inSize; /* size of input data */
/*
** ===================================================================
**     Method      :  Rng1Gal_Put (component RingBufferUInt8)
**     Description :
**         Puts a new element into the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**         elem            - New element to be put into the buffer
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte Rng1Gal_Put(byte elem)
{
  byte res = ERR_OK;

  EnterCritical();
  if (Rng1Gal_inSize==Rng1Gal_BUF_SIZE) {
    res = ERR_TXFULL;
  } else {
    Rng1Gal_buffer[Rng1Gal_inIdx] = elem;
    Rng1Gal_inSize++;
    Rng1Gal_inIdx++;
    if (Rng1Gal_inIdx==Rng1Gal_BUF_SIZE) {
      Rng1Gal_inIdx = 0;
    }
  }
  ExitCritical();
  return res;
}

/*
** ===================================================================
**     Method      :  Rng1Gal_Get (component RingBufferUInt8)
**     Description :
**         Removes an element from the buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**       * elemP           - Pointer to where to store the received
**                           element
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
byte Rng1Gal_Get(byte *elemP)
{
  byte res = ERR_OK;

  EnterCritical();
  if (Rng1Gal_inSize==0) {
    res = ERR_RXEMPTY;
  } else {
    *elemP = Rng1Gal_buffer[Rng1Gal_outIdx];
    Rng1Gal_inSize--;
    Rng1Gal_outIdx++;
    if (Rng1Gal_outIdx==Rng1Gal_BUF_SIZE) {
      Rng1Gal_outIdx = 0;
    }
  }
  ExitCritical();
  return res;
}

/*
** ===================================================================
**     Method      :  Rng1Gal_NofElements (component RingBufferUInt8)
**     Description :
**         Returns the actual number of elements in the buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
byte Rng1Gal_NofElements(void)
{
  return Rng1Gal_inSize;
}

/*
** ===================================================================
**     Method      :  Rng1Gal_NofFreeElements (component RingBufferUInt8)
**     Description :
**         Returns the actual number of free elements/space in the
**         buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of elements in the buffer.
** ===================================================================
*/
byte Rng1Gal_NofFreeElements(void)
{
  return (byte)(Rng1Gal_BUF_SIZE-Rng1Gal_inSize);
}

/*
** ===================================================================
**     Method      :  Rng1Gal_Init (component RingBufferUInt8)
**     Description :
**         Initializes the data structure
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void Rng1Gal_Init(void)
{
  Rng1Gal_inIdx = 0;
  Rng1Gal_outIdx = 0;
  Rng1Gal_inSize = 0;
}

/* END Rng1Gal. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
